# Generated by Django 2.2.6 on 2020-01-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='type_of_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal_data.TypeOfAnimal'),
        ),
    ]
